const placementImages = {
  sonali:  "placement/sonali.jpg",
  rashmi:  "placement/rashmi.jpg",
  nitesh:  "placement/nitesh.jpg",
  manoj:   "placement/manoj.jpg",
  nandu:   "placement/nandu.jpg",
  ishvar1: "placement/ishvar1.jpg",
  Monali:  "placement/Monali.jpg",
  rajat:   "placement/rajat.jpg",
  snehal:  "placement/snehal.jpg",
  akshay:  "placement/akshay.jpg",
  "Adesh Yelmame": "placement/Adesh Yelmame.jpeg",
  "Avinash Kinkrale": "placement/Avinash Kinkrale.jpeg",
  "Shital Gawali": "placement/Shital Gawali.jpeg",
  "Omkar Mane": "placement/Omkar Mane.jpeg",
  "Shubham Rotte": "placement/Shubham Rotte.jpeg",
  "Omkar Hatte": "placement/Omkar Hatte .jpeg",
  "Ganesh Mali": "placement/Ganesh Mali.jpeg",
  "Keshav Sawant": "placement/Keshav Sawant.jpeg",
  "Nikhil Avhad": "placement/Nikhil Avhad.jpeg",
  "Sachin Chikte": "placement/Sachin Chikte.jpeg",
  "Harshada Kamble": "placement/Harshada Kamble.jpeg",
  "Ashish Birajdar": "placement/Ashish Birajdar .jpeg",
};
